name: Compile Blog HTML From Markdown Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
        pip install beautifulsoup4
        pip install pygments

    - name: Run scripts
      run: cd scripts && python convert_markdown_posts.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add .
        git commit -m "Update HTML and posts list"
        
        git remote add origin_with_token "https://$GITHUB_ACTOR:$BLOG_TOKEN@github.com/$GITHUB_REPOSITORY"
        git push --set-upstream origin_with_token main
